esphome:
  name: muas

esp32:
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret "wifi_ssid"
  password: !secret "wifi_password"

captive_portal:

substitutions:
  max_voltage: "10"
  exhaust_fan_threshold_low: "2"
  makuep_air_fan_max_speed: "30"

switch:
  - platform: gpio
    pin: GPIO26
    inverted: true
    name: Makeup Air Damper
    id: makeup_air_damper
 
sensor:
  - platform: adc
    pin: GPIO36
    id: exhaust_hood_voltage
    name: "Exhaust Hood Voltage"
    update_interval: 5s
    attenuation: auto
    filters:
      # (49254/47000) * (10 / 3.3)
      - multiply: 3.1757
    on_value:
      then:
        - script.execute: set_fan_state 

output:
  - platform: ledc
    pin: GPIO25
    id: makeup_air_fan_pwm_output
    frequency: 3000Hz

fan:
  - platform: speed
    output: makeup_air_fan_pwm_output
    id: makeup_air_fan
    name: Makeup Air Fan

script:
  - id: set_fan_state
    then:
      - if:
          condition:
            lambda: |-
              return id(exhaust_hood_voltage).state < id(${exhaust_fan_threshold_low});
          then:
            - fan.turn_off: makeup_air_fan
            - switch.turn_off: makeup_air_damper
          else:
            - switch.turn_on: makeup_air_damper
            - delay: 10s
            - fan.turn_on:
                id:  makeup_air_fan
                speed: !lambda |-
                  float calc_speed = id(exhaust_hood_voltage).state / id(${max_voltage}) * id(${makuep_air_fan_max_speed}) * 1.0;
                  ESP_LOGD("Makeup Air Fan Speed Calc", "calculated speed = %f", calc_speed);
                  return calc_speed;





















